<?php

declare(strict_types=1);

namespace App\Services\Solar;

use App\Contracts\Events\EventDispatcherInterface;
use App\Contracts\Logging\ContextualLoggerInterface;
use App\Contracts\Solar\SolarProposalServiceInterface;
use App\Enums\DocumentStatus;
use App\Models\Manufacturing\Bom;
use App\Models\Manufacturing\BomVariantGroup;
use App\Models\Sales\Quotation;
use App\Models\Solar\IndonesiaSolarData;
use App\Models\Solar\SolarProposal;
use App\Services\Base\BaseService;
use App\Services\Sales\QuotationService;

class SolarProposalService extends BaseService implements SolarProposalServiceInterface
{
    public function __construct(
        protected SolarCalculationService $calculator,
        protected QuotationService $quotationService,
        EventDispatcherInterface $eventDispatcher,
        ContextualLoggerInterface $logger
    ) {
        parent::__construct($eventDispatcher, $logger);
    }

    /**
     * Create a new solar proposal.
     *
     * Includes retry mechanism for race condition handling on proposal number generation.
     *
     * @param  array<string, mixed>  $data
     */
    public function create(array $data): SolarProposal
    {
        $maxRetries = 3;
        $attempt = 0;

        while ($attempt < $maxRetries) {
            try {
                return $this->executeInTransaction('create', function () use ($data) {
                    // Set defaults - number generated by model observer
                    $data['status'] = DocumentStatus::Draft;
                    $data['created_by'] = $this->getUserId();
                    $data['performance_ratio'] = $data['performance_ratio'] ?? 0.80;

                    // Set default validity (30 days)
                    if (empty($data['valid_until'])) {
                        $data['valid_until'] = now()->addDays(30);
                    }

                    // Lookup solar data if province/city provided but not peak_sun_hours
                    if (empty($data['peak_sun_hours']) && ! empty($data['province']) && ! empty($data['city'])) {
                        $solarData = $this->calculator->getSolarDataByLocation($data['province'], $data['city']);
                        if ($solarData) {
                            $data['peak_sun_hours'] = $solarData->peak_sun_hours;
                            $data['solar_irradiance'] = $solarData->solar_irradiance_kwh_m2_day;
                        }
                    }

                    // Create proposal
                    $proposal = SolarProposal::create($data);

                    return $proposal->load(['contact', 'creator']);
                }, ['contact_id' => $data['contact_id'] ?? null]);
            } catch (\Illuminate\Database\QueryException $e) {
                // Check if it's a duplicate key violation (PostgreSQL: 23505)
                if ($e->getCode() === '23505' && str_contains($e->getMessage(), 'proposal_number')) {
                    $attempt++;
                    if ($attempt >= $maxRetries) {
                        throw new \RuntimeException('Gagal membuat nomor proposal setelah beberapa percobaan. Silakan coba lagi.');
                    }
                    // Small delay before retry
                    usleep(50000); // 50ms

                    continue;
                }
                throw $e;
            }
        }

        throw new \RuntimeException('Gagal membuat proposal.');
    }

    /**
     * Update a solar proposal.
     *
     * @param  array<string, mixed>  $data
     */
    public function update(SolarProposal $proposal, array $data): SolarProposal
    {
        if (! $proposal->isEditable()) {
            throw \App\Exceptions\Domain\DocumentLockedException::cannotEdit($proposal, 'Proposal hanya dapat diedit dalam status draft.');
        }

        return $this->executeInTransaction('update', function () use ($proposal, $data) {
            // Update solar data if location changed
            if (
                (isset($data['province']) || isset($data['city'])) &&
                empty($data['peak_sun_hours'])
            ) {
                $province = $data['province'] ?? $proposal->province;
                $city = $data['city'] ?? $proposal->city;

                if ($province && $city) {
                    $solarData = $this->calculator->getSolarDataByLocation($province, $city);
                    if ($solarData) {
                        $data['peak_sun_hours'] = $solarData->peak_sun_hours;
                        $data['solar_irradiance'] = $solarData->solar_irradiance_kwh_m2_day;
                    }
                }
            }

            // Auto-attach BOM when variant_group_id is set/changed
            if (
                isset($data['variant_group_id']) &&
                $data['variant_group_id'] !== $proposal->variant_group_id
            ) {
                $variantGroup = BomVariantGroup::with('activeBoms')->find($data['variant_group_id']);
                if ($variantGroup) {
                    // Auto-select the primary (recommended) BOM if not explicitly set
                    if (empty($data['selected_bom_id'])) {
                        $primaryBom = $variantGroup->primaryBom();
                        if ($primaryBom) {
                            $data['selected_bom_id'] = $primaryBom->id;
                            // Extract capacity from BOM if not already set
                            if (empty($data['system_capacity_kwp']) && empty($proposal->system_capacity_kwp)) {
                                $data['system_capacity_kwp'] = $this->extractCapacityFromBom($primaryBom);
                            }
                        }
                    }
                }
            }

            $proposal->fill($data);
            $proposal->save();

            return $proposal->fresh(['contact', 'creator', 'variantGroup', 'selectedBom']);
        }, ['proposal_id' => $proposal->id]);
    }

    /**
     * Delete a solar proposal.
     */
    public function delete(SolarProposal $proposal): bool
    {
        if ($proposal->status !== DocumentStatus::Draft) {
            throw \App\Exceptions\Domain\DocumentLockedException::cannotDelete($proposal, 'Hanya proposal draft yang dapat dihapus.');
        }

        return $proposal->delete();
    }

    /**
     * Calculate and update all proposal values.
     *
     * This should be called after updating site info, consumption, or system selection.
     */
    public function calculateProposal(SolarProposal $proposal): SolarProposal
    {
        if (! $proposal->isEditable()) {
            throw \App\Exceptions\Domain\DocumentLockedException::cannotEdit($proposal, 'Proposal hanya dapat dihitung ulang dalam status draft.');
        }

        return $this->executeInTransaction('calculate_proposal', function () use ($proposal) {
            // Get system capacity from selected BOM or calculate recommended size
            $capacityKwp = $proposal->system_capacity_kwp;

            if ($capacityKwp === null && $proposal->monthly_consumption_kwh && $proposal->peak_sun_hours) {
                $capacityKwp = $this->calculator->recommendSystemSize(
                    (float) $proposal->monthly_consumption_kwh,
                    (float) $proposal->peak_sun_hours,
                    1.0, // 100% offset target
                    (float) $proposal->performance_ratio
                );
                $proposal->system_capacity_kwp = $capacityKwp;
            }

            // Calculate annual production
            if ($capacityKwp && $proposal->peak_sun_hours) {
                $baseProduction = $this->calculator->calculateAnnualProduction(
                    (float) $capacityKwp,
                    (float) $proposal->peak_sun_hours,
                    (float) $proposal->performance_ratio
                );

                // Apply orientation factor
                if ($proposal->roof_orientation) {
                    $baseProduction = $this->calculator->applyOrientationFactor(
                        $baseProduction,
                        $proposal->roof_orientation
                    );
                }

                // Apply shading factor
                if ($proposal->shading_percentage > 0) {
                    $baseProduction = $this->calculator->applyShadingFactor(
                        $baseProduction,
                        (float) $proposal->shading_percentage
                    );
                }

                $proposal->annual_production_kwh = $baseProduction;
            }

            // Calculate financial analysis if we have all required data
            if (
                $proposal->annual_production_kwh &&
                $proposal->electricity_rate &&
                $proposal->selected_bom_id
            ) {
                $systemCost = $proposal->getSystemCost();

                if ($systemCost) {
                    $financialAnalysis = $this->calculator->calculateFinancialAnalysis(
                        (float) $proposal->annual_production_kwh,
                        (float) $proposal->electricity_rate,
                        (float) ($proposal->tariff_escalation_percent ?? 5) / 100,
                        $systemCost
                    );

                    $proposal->financial_analysis = $financialAnalysis;
                }
            }

            // Calculate environmental impact
            if ($proposal->annual_production_kwh) {
                $proposal->environmental_impact = $this->calculator->calculateEnvironmentalImpact(
                    (float) $proposal->annual_production_kwh
                );
            }

            $proposal->save();

            return $proposal->fresh(['contact', 'variantGroup', 'selectedBom']);
        }, ['proposal_id' => $proposal->id]);
    }

    /**
     * Attach a BOM variant group to the proposal.
     *
     * This links the proposal to a set of Budget/Standard/Premium options.
     */
    public function attachVariantGroup(SolarProposal $proposal, int $variantGroupId): SolarProposal
    {
        if (! $proposal->isEditable()) {
            throw \App\Exceptions\Domain\DocumentLockedException::cannotEdit($proposal, 'Proposal hanya dapat diedit dalam status draft.');
        }

        $variantGroup = BomVariantGroup::with('activeBoms')->find($variantGroupId);
        if (! $variantGroup) {
            throw new \App\Exceptions\Domain\EntityNotFoundException('BomVariantGroup', $variantGroupId);
        }

        return $this->executeInTransaction('attach_variant_group', function () use ($proposal, $variantGroup) {
            $proposal->variant_group_id = $variantGroup->id;

            // Auto-select the primary (recommended) BOM if available
            $primaryBom = $variantGroup->primaryBom();
            if ($primaryBom) {
                $proposal->selected_bom_id = $primaryBom->id;
                $proposal->system_capacity_kwp = $this->extractCapacityFromBom($primaryBom);
            }

            $proposal->save();

            // Recalculate with new system
            return $this->calculateProposal($proposal);
        }, ['proposal_id' => $proposal->id, 'variant_group_id' => $variantGroup->id]);
    }

    /**
     * Select a specific BOM from the variant group.
     */
    public function selectBom(SolarProposal $proposal, int $bomId): SolarProposal
    {
        if (! $proposal->isEditable()) {
            throw \App\Exceptions\Domain\DocumentLockedException::cannotEdit($proposal, 'Proposal hanya dapat diedit dalam status draft.');
        }

        $bom = Bom::find($bomId);
        if (! $bom) {
            throw new \App\Exceptions\Domain\EntityNotFoundException('Bom', $bomId);
        }

        // Verify BOM belongs to the attached variant group (if any)
        if ($proposal->variant_group_id && $bom->variant_group_id !== $proposal->variant_group_id) {
            throw \App\Exceptions\Domain\BusinessRuleException::operationNotAllowed(
                'memilih BOM',
                'BOM tidak termasuk dalam variant group yang dipilih'
            );
        }

        return $this->executeInTransaction('select_bom', function () use ($proposal, $bom) {
            $proposal->selected_bom_id = $bom->id;
            $proposal->system_capacity_kwp = $this->extractCapacityFromBom($bom);

            // If no variant group attached, attach it now
            if (! $proposal->variant_group_id && $bom->variant_group_id) {
                $proposal->variant_group_id = $bom->variant_group_id;
            }

            $proposal->save();

            return $this->calculateProposal($proposal);
        }, ['proposal_id' => $proposal->id, 'bom_id' => $bom->id]);
    }

    /**
     * Mark proposal as sent to customer.
     */
    public function send(SolarProposal $proposal): SolarProposal
    {
        $stateMachine = $proposal->stateMachine();

        if (! $stateMachine->canSend()) {
            throw \App\Exceptions\Domain\StateTransitionException::wrongStateForOperation(
                'Proposal Solar',
                'dikirim',
                $proposal->status->value,
                'draft dengan variant group dan kalkulasi lengkap'
            );
        }

        return $this->executeInTransaction('send', function () use ($proposal) {
            // Use state machine for status transition
            // State machine handles sent_at, public_token, public_token_expires_at
            $proposal->transitionTo(DocumentStatus::Sent, $this->getUserId());

            return $proposal->fresh();
        }, ['proposal_id' => $proposal->id]);
    }

    /**
     * Mark proposal as accepted by customer.
     *
     * @param  int|null  $selectedBomId  The BOM variant customer selected (if multi-option)
     */
    public function accept(SolarProposal $proposal, ?int $selectedBomId = null): SolarProposal
    {
        $stateMachine = $proposal->stateMachine();

        if (! $stateMachine->canAccept()) {
            throw \App\Exceptions\Domain\StateTransitionException::wrongStateForOperation(
                'Proposal Solar',
                'diterima',
                $proposal->status->value,
                'sent'
            );
        }

        return $this->executeInTransaction('accept', function () use ($proposal, $selectedBomId) {
            // Update selected BOM if customer chose a different variant
            if ($selectedBomId && $selectedBomId !== $proposal->selected_bom_id) {
                $bom = Bom::find($selectedBomId);
                if ($bom && $bom->variant_group_id === $proposal->variant_group_id) {
                    $proposal->selected_bom_id = $selectedBomId;
                    $proposal->save();
                }
            }

            // Use state machine for status transition
            // State machine handles accepted_at
            $proposal->transitionTo(DocumentStatus::Accepted);

            return $proposal->fresh(['contact', 'selectedBom']);
        }, ['proposal_id' => $proposal->id]);
    }

    /**
     * Mark proposal as rejected by customer.
     */
    public function reject(SolarProposal $proposal, ?string $reason = null): SolarProposal
    {
        $stateMachine = $proposal->stateMachine();

        if (! $stateMachine->canReject()) {
            throw \App\Exceptions\Domain\StateTransitionException::wrongStateForOperation(
                'Proposal Solar',
                'ditolak',
                $proposal->status->value,
                'sent'
            );
        }

        return $this->executeInTransaction('reject', function () use ($proposal, $reason) {
            // Use state machine for status transition
            // State machine handles rejected_at and rejection_reason via context
            $proposal->transitionTo(DocumentStatus::Rejected, null, ['rejection_reason' => $reason]);

            return $proposal->fresh();
        }, ['proposal_id' => $proposal->id]);
    }

    /**
     * Convert accepted proposal to a quotation.
     *
     * Creates a quotation from the selected BOM with the proposal's pricing.
     */
    public function convertToQuotation(SolarProposal $proposal): Quotation
    {
        if (! $proposal->canConvert()) {
            throw \App\Exceptions\Domain\StateTransitionException::wrongStateForOperation(
                'Proposal Solar',
                'dikonversi ke quotation',
                $proposal->status->value,
                'accepted dengan BOM yang dipilih'
            );
        }

        return $this->executeInTransaction('convert_to_quotation', function () use ($proposal) {
            $bom = $proposal->selectedBom;

            // Create quotation from the selected BOM
            $quotation = $this->quotationService->createFromBom([
                'bom_id' => $bom->id,
                'contact_id' => $proposal->contact_id,
                'expand_items' => false, // Keep as single line for solar systems
                'subject' => 'Sistem Panel Surya - '.$proposal->site_name,
                'notes' => $this->buildQuotationNotes($proposal),
                'reference' => $proposal->proposal_number,
            ]);

            // Link proposal to quotation
            $proposal->converted_quotation_id = $quotation->id;
            $proposal->save();

            return $quotation;
        }, ['proposal_id' => $proposal->id]);
    }

    /**
     * Get solar data lookup for location.
     */
    public function lookupSolarData(string $province, string $city): ?IndonesiaSolarData
    {
        return $this->calculator->getSolarDataByLocation($province, $city);
    }

    /**
     * Get solar data by coordinates.
     */
    public function lookupSolarDataByCoordinates(float $latitude, float $longitude): ?IndonesiaSolarData
    {
        return $this->calculator->getSolarDataByCoordinates($latitude, $longitude);
    }

    // ========================================
    // Helper Methods
    // ========================================

    /**
     * Extract system capacity from BOM.
     *
     * Looks for kWp in the BOM name or calculates from panel count.
     */
    protected function extractCapacityFromBom(Bom $bom): ?float
    {
        // Try to extract from BOM name (e.g., "10 kWp Solar System")
        if (preg_match('/(\d+(?:\.\d+)?)\s*k[Ww][Pp]/i', $bom->name, $matches)) {
            return (float) $matches[1];
        }

        // Try variant name
        if ($bom->variant_name && preg_match('/(\d+(?:\.\d+)?)\s*k[Ww][Pp]/i', $bom->variant_name, $matches)) {
            return (float) $matches[1];
        }

        return null;
    }

    /**
     * Build notes for quotation from proposal data.
     */
    protected function buildQuotationNotes(SolarProposal $proposal): string
    {
        $notes = [];

        $notes[] = "Dibuat dari Solar Proposal: {$proposal->proposal_number}";
        $notes[] = '';

        if ($proposal->site_address) {
            $notes[] = "Lokasi: {$proposal->site_address}";
        }

        if ($proposal->system_capacity_kwp) {
            $notes[] = "Kapasitas Sistem: {$proposal->system_capacity_kwp} kWp";
        }

        if ($proposal->annual_production_kwh) {
            $notes[] = 'Estimasi Produksi: '.number_format((float) $proposal->annual_production_kwh).' kWh/tahun';
        }

        if ($proposal->getPaybackPeriod()) {
            $notes[] = "Payback Period: {$proposal->getPaybackPeriod()} tahun";
        }

        if ($proposal->getRoi()) {
            $notes[] = "ROI (25 tahun): {$proposal->getRoi()}%";
        }

        return implode("\n", $notes);
    }
}
