<?php

declare(strict_types=1);

namespace App\Services\Base\Traits;

use App\Enums\DocumentStatus;
use App\Exceptions\Domain\DocumentLockedException;
use Illuminate\Database\Eloquent\Model;

/**
 * Document management for services.
 *
 * Provides CRUD operations, items management, status validation,
 * and totals calculation.
 *
 * Note: Document number generation is handled by model boot() methods
 * via App\Domain\Shared\DocumentNumbers helper.
 *
 * Services using this trait must implement:
 * - getModelClass()
 * - getItemRelation()
 */
trait WithDocuments
{
    /**
     * Get model class name.
     *
     * @return class-string<Model>
     */
    abstract protected function getModelClass(): string;

    /**
     * Get item relationship name.
     */
    abstract protected function getItemRelation(): string;

    /**
     * Get default data for new documents.
     *
     * @return array<string, mixed>
     */
    protected function getDefaultData(): array
    {
        return [
            'currency' => 'IDR',
            'exchange_rate' => 1,
            'tax_rate' => config('accounting.tax.default_rate', 11.00),
            'subtotal' => 0,
            'discount_amount' => 0,
            'tax_amount' => 0,
            'total_amount' => 0,
            'base_currency_total' => 0,
        ];
    }

    /**
     * Get initial status for new documents.
     */
    protected function getInitialStatus(): DocumentStatus
    {
        return DocumentStatus::Draft;
    }

    /**
     * Get relations to load after create/update.
     *
     * @return array<string>
     */
    protected function getEagerLoadRelations(): array
    {
        return [$this->getItemRelation(), 'contact'];
    }

    /**
     * Create a new document.
     *
     * Note: Document number is auto-generated by model's boot() method.
     *
     * Override in child class for public access.
     *
     * @param  array<string, mixed>  $data
     */
    protected function createDocument(array $data): Model
    {
        return $this->executeInTransaction('create', function () use ($data) {
            $items = $data['items'] ?? [];
            unset($data['items']);

            $data = array_merge($this->getDefaultData(), $data);
            $data['created_by'] = $data['created_by'] ?? $this->getUserId();
            $data['status'] = $this->getInitialStatus();

            $document = $this->getModelClass()::create($data);

            if (! empty($items)) {
                $this->createItems($document, $items);
            }

            $this->recalculateTotals($document);

            return $this->loadRelations($document);
        }, ['contact_id' => $data['contact_id'] ?? null]);
    }

    /**
     * Update a document.
     *
     * Override in child class for public access.
     *
     * @param  array<string, mixed>  $data
     *
     * @throws DocumentLockedException
     */
    protected function updateDocument(Model $document, array $data): Model
    {
        $this->validateEditable($document);

        return $this->executeInTransaction('update', function () use ($document, $data) {
            $items = $data['items'] ?? null;
            unset($data['items']);

            $document->update($data);

            if ($items !== null) {
                $document->{$this->getItemRelation()}()->delete();
                $this->createItems($document, $items);
            }

            $this->recalculateTotals($document);

            return $this->loadRelations($document);
        }, ['document_id' => $document->id]);
    }

    /**
     * Delete a document.
     *
     * Override in child class for public access.
     *
     *
     * @throws DocumentLockedException
     */
    protected function deleteDocument(Model $document): bool
    {
        $this->validateDeletable($document);

        return $this->executeInTransaction('delete', function () use ($document) {
            $document->{$this->getItemRelation()}()->delete();

            $document->delete();

            return true;
        }, ['document_id' => $document->id]);
    }

    /**
     * Create items for document.
     *
     * @param  array<int, array<string, mixed>>  $items
     */
    protected function createItems(Model $document, array $items): void
    {
        foreach ($items as $itemData) {
            $document->{$this->getItemRelation()}()->create($itemData);
        }
    }

    /**
     * Recalculate document totals.
     */
    protected function recalculateTotals(Model $document): void
    {
        $document->refresh();

        if (method_exists($document, 'calculateTotals')) {
            $document->calculateTotals();
            $document->save();
        }
    }

    /**
     * Load standard relations on document.
     */
    protected function loadRelations(Model $document): Model
    {
        return $document->fresh($this->getEagerLoadRelations());
    }

    /**
     * Validate document is editable.
     *
     *
     * @throws DocumentLockedException
     */
    protected function validateEditable(Model $document): void
    {
        if ($document->status !== DocumentStatus::Draft) {
            throw DocumentLockedException::cannotEdit(
                $document,
                'Hanya dokumen draft yang dapat diubah.'
            );
        }
    }

    /**
     * Validate document is deletable.
     *
     *
     * @throws DocumentLockedException
     */
    protected function validateDeletable(Model $document): void
    {
        if ($document->status !== DocumentStatus::Draft) {
            throw DocumentLockedException::cannotDelete(
                $document,
                'Hanya dokumen draft yang dapat dihapus.'
            );
        }
    }
}
