<?php

declare(strict_types=1);

namespace App\Services\Solar\Proposal;

use App\Contracts\Events\EventDispatcherInterface;
use App\Contracts\Logging\ContextualLoggerInterface;
use App\Enums\DocumentStatus;
use App\Models\Manufacturing\Bom;
use App\Models\Manufacturing\BomVariantGroup;
use App\Models\Solar\SolarProposal;
use App\Services\Base\Traits\WithEventDispatching;
use App\Services\Base\Traits\WithOperationContext;
use App\Services\Base\Traits\WithTransaction;
use App\Services\Solar\SolarCalculationService;

/**
 * Handles CRUD operations for solar proposals.
 *
 * Extracted from SolarProposalService as part of the Coordinator Pattern refactoring.
 *
 * @see \App\Services\Solar\SolarProposalService The coordinator service
 */
class SolarProposalCrudService
{
    use WithEventDispatching;
    use WithOperationContext;
    use WithTransaction;

    protected EventDispatcherInterface $eventDispatcher;

    protected ContextualLoggerInterface $logger;

    public function __construct(
        EventDispatcherInterface $eventDispatcher,
        ContextualLoggerInterface $logger,
        protected SolarCalculationService $calculator,
    ) {
        $this->eventDispatcher = $eventDispatcher;
        $this->logger = $logger;
    }

    /**
     * Create a new solar proposal.
     *
     * Includes retry mechanism for race condition handling on proposal number generation.
     *
     * @param  array<string, mixed>  $data
     */
    public function create(array $data): SolarProposal
    {
        $maxRetries = 3;
        $attempt = 0;

        while ($attempt < $maxRetries) {
            try {
                return $this->executeInTransaction('create', function () use ($data) {
                    // Set defaults - number generated by model observer
                    $data['status'] = DocumentStatus::Draft;
                    $data['created_by'] = $this->getUserId();
                    $data['performance_ratio'] = $data['performance_ratio'] ?? 0.80;

                    // Set default validity (30 days)
                    if (empty($data['valid_until'])) {
                        $data['valid_until'] = now()->addDays(30);
                    }

                    // Lookup solar data if province/city provided but not peak_sun_hours
                    if (empty($data['peak_sun_hours']) && ! empty($data['province']) && ! empty($data['city'])) {
                        $solarData = $this->calculator->getSolarDataByLocation($data['province'], $data['city']);
                        if ($solarData) {
                            $data['peak_sun_hours'] = $solarData->peak_sun_hours;
                            $data['solar_irradiance'] = $solarData->solar_irradiance_kwh_m2_day;
                        }
                    }

                    // Create proposal
                    $proposal = SolarProposal::create($data);

                    return $proposal->load(['contact', 'creator']);
                }, ['contact_id' => $data['contact_id'] ?? null]);
            } catch (\Illuminate\Database\QueryException $e) {
                // Check if it's a duplicate key violation (PostgreSQL: 23505)
                if ($e->getCode() === '23505' && str_contains($e->getMessage(), 'proposal_number')) {
                    $attempt++;
                    if ($attempt >= $maxRetries) {
                        throw new \RuntimeException('Gagal membuat nomor proposal setelah beberapa percobaan. Silakan coba lagi.');
                    }
                    // Small delay before retry
                    usleep(50000); // 50ms

                    continue;
                }
                throw $e;
            }
        }

        throw new \RuntimeException('Gagal membuat proposal.');
    }

    /**
     * Update a solar proposal.
     *
     * @param  array<string, mixed>  $data
     */
    public function update(SolarProposal $proposal, array $data): SolarProposal
    {
        if (! $proposal->isEditable()) {
            throw \App\Exceptions\Domain\DocumentLockedException::cannotEdit($proposal, 'Proposal hanya dapat diedit dalam status draft.');
        }

        return $this->executeInTransaction('update', function () use ($proposal, $data) {
            // Update solar data if location changed
            if (
                (isset($data['province']) || isset($data['city'])) &&
                empty($data['peak_sun_hours'])
            ) {
                $province = $data['province'] ?? $proposal->province;
                $city = $data['city'] ?? $proposal->city;

                if ($province && $city) {
                    $solarData = $this->calculator->getSolarDataByLocation($province, $city);
                    if ($solarData) {
                        $data['peak_sun_hours'] = $solarData->peak_sun_hours;
                        $data['solar_irradiance'] = $solarData->solar_irradiance_kwh_m2_day;
                    }
                }
            }

            // Auto-attach BOM when variant_group_id is set/changed
            if (
                isset($data['variant_group_id']) &&
                $data['variant_group_id'] !== $proposal->variant_group_id
            ) {
                $variantGroup = BomVariantGroup::with('activeBoms')->find($data['variant_group_id']);
                if ($variantGroup) {
                    // Auto-select the primary (recommended) BOM if not explicitly set
                    if (empty($data['selected_bom_id'])) {
                        $primaryBom = $variantGroup->primaryBom();
                        if ($primaryBom) {
                            $data['selected_bom_id'] = $primaryBom->id;
                            // Extract capacity from BOM if not already set
                            if (empty($data['system_capacity_kwp']) && empty($proposal->system_capacity_kwp)) {
                                $data['system_capacity_kwp'] = $this->extractCapacityFromBom($primaryBom);
                            }
                        }
                    }
                }
            }

            $proposal->fill($data);
            $proposal->save();

            return $proposal->fresh(['contact', 'creator', 'variantGroup', 'selectedBom']);
        }, ['proposal_id' => $proposal->id]);
    }

    /**
     * Delete a solar proposal.
     */
    public function delete(SolarProposal $proposal): bool
    {
        if ($proposal->status !== DocumentStatus::Draft) {
            throw \App\Exceptions\Domain\DocumentLockedException::cannotDelete($proposal, 'Hanya proposal draft yang dapat dihapus.');
        }

        return $proposal->delete();
    }

    /**
     * Extract system capacity from BOM.
     *
     * Looks for kWp in the BOM name or calculates from panel count.
     */
    protected function extractCapacityFromBom(Bom $bom): ?float
    {
        // Try to extract from BOM name (e.g., "10 kWp Solar System")
        if (preg_match('/(\d+(?:\.\d+)?)\s*k[Ww][Pp]/i', $bom->name, $matches)) {
            return (float) $matches[1];
        }

        // Try variant name
        if ($bom->variant_name && preg_match('/(\d+(?:\.\d+)?)\s*k[Ww][Pp]/i', $bom->variant_name, $matches)) {
            return (float) $matches[1];
        }

        return null;
    }
}
